### ISSUE TITLE
Discover SR-IOV capable network interfaces

### ISSUE THREAD

**Issue by ConnorDoyle** [kubernetes-incubator/node-feature-discovery#35]
cc @thed00de @rkamudhan @swatisehgal @balajismaniam

**Comment by rkamudhan** [comment]
@ConnorDoyle, we are working on it. @swatisehgal can you provide more details on the design.

**Comment by ConnorDoyle** [comment]
@rkamudhan OK, thanks! If you could use any help please just reach out.

**Comment by swatisehgal** [comment]
Work in progress! Will provide details early next week.

**Comment by swatisehgal** [comment]
In order to be able to discover SR-IOV capability in the NIC on a node, our current approach is to query the sysfs of the node.  There are two SRIOV related files, sysfile /sys/class/net/<network Interface>/device/sriov_numvfs and sysfile /sys/class/net/<network Interface>/device/sriov_totalvfs that store the configured number of VFs for a specific PF and maximum possible VFs for PFs respectively. These files are NIC vendor agnostic and allow configuration of VFs for specific PFs. The
code for SR-IOV discovery would be implemented in Discover() function of networkSource ( which implements FeatureSource ). We will be looking into implementation and incorporating Opaque integer resources into NFD too. Its currently under discussion.

**Comment by balajismaniam** [comment]
Thanks for update. 
> We will be looking into implementation and incorporating Opaque integer resources into NFD too. Its currently under discussion. 
Right now, NFD discovers only binary resources. We will need to discuss with the community before enhancing the scope of NFD.

**Comment by ConnorDoyle** [comment]
Sent an email to the dev list to revive the discussion and directed folks to comment in issue #45.
